import type { Band, Exposure, Ground, RegionId, Species } from "./types";

export const REGIONS: { id: RegionId; label: string }[] = [
  { id: "outer-banks", label: "North Carolina" },
  { id: "chesapeake", label: "Chesapeake" },
  { id: "southeast", label: "Southeast" },
  { id: "florida", label: "Florida" },
  { id: "gulf", label: "Gulf" },
  { id: "northeast", label: "Northeast" },
  { id: "pacific", label: "Pacific" },
];

function blob(lat: number, lng: number, rLat: number, rLng: number): [number, number][] {
  const pts: [number, number][] = [];
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 3) * i - Math.PI / 6;
    const j = 0.86 + ((i * 3) % 4) * 0.05;
    pts.push([
      Math.round((lat + Math.sin(a) * rLat * j) * 1000) / 1000,
      Math.round((lng + Math.cos(a) * rLng * j) * 1000) / 1000,
    ]);
  }
  return pts;
}

function sp(name: string, months: number[], note: string): Species {
  return { name, months, note };
}

function ground(
  id: string,
  name: string,
  region: RegionId,
  band: Band,
  exposure: Exposure,
  lat: number,
  lng: number,
  rLat: number,
  rLng: number,
  depth: string,
  structure: string,
  tactic: string,
  species: Species[],
): Ground {
  return {
    id,
    name,
    region,
    band,
    exposure,
    lat,
    lng,
    ring: blob(lat, lng, rLat, rLng),
    depth,
    structure,
    tactic,
    species,
  };
}

export const GROUNDS: Ground[] = [
  ground(
    "cbbt",
    "Chesapeake Bay Bridge-Tunnel",
    "chesapeake",
    "nearshore",
    "coastal",
    36.98,
    -76.1,
    0.12,
    0.09,
    "20–55 ft",
    "Pilings, rock islands, tube",
    "Fish the upcurrent side of the islands. Live bait or bucktails when the tide is moving; slack is a coffee break.",
    [
      sp("Striped bass", [3, 4, 5, 10, 11, 12], "Spring trophies and the fall run on eels and plugs."),
      sp("Cobia", [5, 6, 7, 8, 9], "Sight-fish buoys and the islands on calm days."),
      sp("Sheepshead", [4, 5, 6, 7, 8, 9, 10], "Fiddler crabs tight to the concrete."),
      sp("Flounder", [5, 6, 7, 8, 9], "Drifting minnows along the tube."),
      sp("Spadefish", [6, 7, 8, 9], "Chum the islands and drop clam."),
      sp("Red drum", [5, 6, 7, 8, 9, 10], "Bulls on the shoals in spring and fall."),
      sp("Tautog", [11, 12, 1, 2, 3, 4], "Green crab on the rock when the bass are gone."),
    ],
  ),
  ground(
    "lynnhaven",
    "Lynnhaven & Rudee",
    "chesapeake",
    "inshore",
    "protected",
    36.89,
    -76.05,
    0.07,
    0.08,
    "4–18 ft",
    "Inlet, docks, grass edges",
    "Work the last of the incoming into the grass, then the first of the outgoing at the inlet mouth.",
    [
      sp("Speckled trout", [4, 5, 6, 9, 10, 11], "Soft plastics on grass points at dawn."),
      sp("Red drum", [5, 6, 7, 8, 9, 10], "Puppy drum on finger mullet and gold spoons."),
      sp("Flounder", [5, 6, 7, 8, 9], "Mud minnows along the channel edge."),
      sp("Bluefish", [5, 6, 7, 8, 9, 10], "Small metals when birds are working."),
      sp("Striped bass", [3, 4, 11, 12], "Schoolies in the fall inside Rudee."),
    ],
  ),
  ground(
    "hampton",
    "Hampton Roads",
    "chesapeake",
    "inshore",
    "protected",
    36.98,
    -76.33,
    0.08,
    0.1,
    "12–40 ft",
    "Bridge pilings, channel edges",
    "The HRBT and Monitor-Merrimac pilings fish like a smaller CBBT. Stay out of the ship channel.",
    [
      sp("Sheepshead", [4, 5, 6, 7, 8, 9, 10], "Crabs on the downcurrent pilings."),
      sp("Striped bass", [3, 4, 5, 10, 11, 12], "Night eels in spring, plugs in the fall."),
      sp("Croaker", [5, 6, 7, 8, 9], "Bottom rigs with bloodworm or fish bites."),
      sp("Spot", [6, 7, 8, 9], "Easy bottom bite for a mixed cooler."),
      sp("Speckled trout", [4, 5, 9, 10, 11], "Around lights and creek mouths."),
    ],
  ),
  ground(
    "york",
    "York River mouth",
    "chesapeake",
    "inshore",
    "protected",
    37.22,
    -76.45,
    0.08,
    0.1,
    "8–30 ft",
    "Drop-offs, oyster bars",
    "Drift the channel bends. The river fishes best on a moving tide and a light northwest or southwest breeze.",
    [
      sp("Striped bass", [3, 4, 5, 10, 11], "Spring run staging, fall schoolies."),
      sp("Speckled trout", [4, 5, 9, 10, 11], "Grass and oyster at the mouth."),
      sp("Red drum", [5, 6, 8, 9, 10], "Puppy drum on the flats off the mouth."),
      sp("Croaker", [5, 6, 7, 8], "Bottom in the channel."),
      sp("Flounder", [5, 6, 7, 8], "Along the deeper edge."),
    ],
  ),
  ground(
    "cape-henry",
    "Cape Henry shoals",
    "chesapeake",
    "nearshore",
    "coastal",
    36.93,
    -75.95,
    0.07,
    0.08,
    "15–40 ft",
    "Shoals, tide rips",
    "The rip on a falling tide stacks bait. Don't anchor in the channel; drift or spot-lock the edge.",
    [
      sp("Red drum", [4, 5, 6, 9, 10], "Bull reds on the shoal in spring."),
      sp("Cobia", [5, 6, 7, 8], "Sight-casting when the water is green-clear."),
      sp("Bluefish", [4, 5, 6, 9, 10], "Metals through the bait balls."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Fast retrieve just under the surface."),
      sp("Striped bass", [4, 5, 11], "When the ocean run is on."),
    ],
  ),
  ground(
    "ches-light",
    "Chesapeake Light",
    "chesapeake",
    "nearshore",
    "open",
    36.91,
    -75.71,
    0.08,
    0.1,
    "40–70 ft",
    "Tower, wrecks, hard bottom",
    "About 14 miles out. Fish the tower shadow and nearby wrecks. Leave a weather window to get home.",
    [
      sp("Cobia", [5, 6, 7, 8, 9], "Sight-fish the buoy line on the way out."),
      sp("Spadefish", [6, 7, 8, 9], "Chum the tower legs."),
      sp("Amberjack", [6, 7, 8, 9], "Live bait on the wrecks. Check size rules."),
      sp("Flounder", [5, 6, 7, 8, 9], "Drifting the hard bottom around the tower."),
      sp("King mackerel", [7, 8, 9], "Slow-troll live bait when the water warms."),
    ],
  ),
  ground(
    "tangier",
    "Tangier Sound",
    "chesapeake",
    "inshore",
    "protected",
    37.85,
    -75.98,
    0.12,
    0.12,
    "6–20 ft",
    "Grass, islands, guts",
    "A small-boat sound. Poling and trolling motors beat a big wake. Watch the skinny water east of the islands.",
    [
      sp("Speckled trout", [4, 5, 6, 9, 10, 11], "The classic fall sound bite."),
      sp("Red drum", [5, 6, 7, 8, 9, 10], "Puppy drum on the grass edges."),
      sp("Striped bass", [4, 5, 10, 11], "Schoolies around the islands."),
      sp("Flounder", [5, 6, 7, 8], "Channel edges of the sound."),
    ],
  ),
  ground(
    "lookout",
    "Point Lookout",
    "chesapeake",
    "inshore",
    "protected",
    38.04,
    -76.32,
    0.07,
    0.08,
    "8–35 ft",
    "Point rip, bridge, channel",
    "The Potomac dumps into the Bay here. Fish the rip on the outgoing and the bridge pilings at night in season.",
    [
      sp("Striped bass", [3, 4, 5, 10, 11, 12], "One of the Bay's better spring and fall points."),
      sp("Speckled trout", [5, 6, 9, 10], "Inside the point on smaller tides."),
      sp("Bluefish", [5, 6, 9, 10], "With the bass in the fall."),
      sp("Croaker", [6, 7, 8], "Daytime bottom bite."),
    ],
  ),
  ground(
    "norfolk-canyon",
    "Norfolk Canyon",
    "chesapeake",
    "offshore",
    "open",
    37.03,
    -74.62,
    0.16,
    0.2,
    "100–1000 ftm",
    "Canyon wall, tile bottom",
    "A real offshore run from Rudee or the Bay. Pick a calm window. Tilefish on the bottom, pelagics on the wall and temperature breaks.",
    [
      sp("Yellowfin tuna", [5, 6, 7, 8, 9, 10], "Troll and chunk the edge when the Gulf Stream bends in."),
      sp("Mahi", [6, 7, 8, 9], "Weedlines and anything floating."),
      sp("White marlin", [7, 8, 9], "Spread of dredges and naked ballyhoo."),
      sp("Blueline tilefish", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "Deep drop. Know the bag limit."),
      sp("Bluefin tuna", [12, 1, 2, 3], "Winter fish when the water is cold and the forecast is kind."),
      sp("Wahoo", [8, 9, 10], "High-speed along the break."),
    ],
  ),
  ground(
    "washington-canyon",
    "Washington Canyon",
    "chesapeake",
    "offshore",
    "open",
    37.42,
    -74.48,
    0.14,
    0.18,
    "80–800 ftm",
    "Canyon mouth, lobes",
    "Often the closer canyon if you leave from Ocean City or Chincoteague. Same rules: weather first, then the temperature break.",
    [
      sp("Yellowfin tuna", [6, 7, 8, 9, 10], "Chunking after a midday troll."),
      sp("Mahi", [6, 7, 8, 9], "Any board or crate on the way."),
      sp("White marlin", [7, 8, 9], "The late-summer canyon bite."),
      sp("Swordfish", [6, 7, 8, 9], "Night deep-drop. Not a first offshore trip."),
      sp("Tilefish", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "Daytime bottom on the slope."),
    ],
  ),
  ground(
    "oregon",
    "Oregon Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    35.77,
    -75.53,
    0.07,
    0.08,
    "8–30 ft",
    "Inlet, bridge, shoals",
    "The inlet moves. Use the markers, not memory. Bridge pilings and the inlet shoulders on a moving tide.",
    [
      sp("Red drum", [4, 5, 6, 9, 10, 11], "Spring bulls on the shoals, puppies inside."),
      sp("Speckled trout", [4, 5, 10, 11], "Sound side of the bridge."),
      sp("Striped bass", [11, 12, 1, 2, 3], "Winter ocean-side when it's calm enough."),
      sp("Bluefish", [4, 5, 10, 11], "With the fall bait."),
      sp("Flounder", [5, 6, 7, 8], "Drifting the inlet channel."),
    ],
  ),
  ground(
    "hatteras-inlet",
    "Hatteras Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    35.2,
    -75.76,
    0.06,
    0.07,
    "6–25 ft",
    "Inlet sloughs",
    "A short, serious inlet. Fish the sloughs on the last of the incoming. If the swell is up, stay in the sound.",
    [
      sp("Red drum", [4, 5, 10, 11], "Sight-fishing the sloughs in clear water."),
      sp("Speckled trout", [4, 5, 10, 11], "Sound-side grass when the ocean is ugly."),
      sp("Bluefish", [4, 5, 10], "Choppers in the fall."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Along the beach when it's calm."),
    ],
  ),
  ground(
    "diamond",
    "Diamond Shoals",
    "outer-banks",
    "nearshore",
    "open",
    35.15,
    -75.4,
    0.1,
    0.14,
    "30–90 ft",
    "Shoal, rips, wrecks",
    "The bend in the Banks. Rips, bait, and everything that eats it. Give the breakers a wide berth.",
    [
      sp("Red drum", [4, 5, 10, 11], "Big fish on the shoal edges."),
      sp("Cobia", [5, 6, 7], "Buoys and rays on the way to the stream."),
      sp("King mackerel", [5, 6, 9, 10], "Slow-troll the color change."),
      sp("Spanish mackerel", [6, 7, 8], "Fast troll in the green water."),
      sp("Amberjack", [5, 6, 7, 8], "Nearby wrecks."),
    ],
  ),
  ground(
    "hatteras-canyon",
    "Hatteras Canyon",
    "outer-banks",
    "offshore",
    "open",
    35.35,
    -74.85,
    0.16,
    0.22,
    "100–1000 ftm",
    "Canyon, Gulf Stream edge",
    "The stream is close here, which is why Hatteras is Hatteras. A short bad forecast gets worse fast.",
    [
      sp("Yellowfin tuna", [4, 5, 6, 7, 8, 9, 10], "A long season when the stream is on the shelf."),
      sp("Blue marlin", [6, 7, 8], "Summer troll. Heavy tackle."),
      sp("White marlin", [7, 8, 9], "With the yellowfin spread."),
      sp("Mahi", [5, 6, 7, 8, 9], "Weedlines between the inlet and the canyon."),
      sp("Wahoo", [8, 9, 10], "First light, high speed."),
      sp("Blackfin tuna", [5, 6, 7, 8, 9], "Smaller feathers in the spread."),
    ],
  ),
  ground(
    "duck",
    "Duck & Kitty Hawk",
    "outer-banks",
    "nearshore",
    "coastal",
    36.17,
    -75.75,
    0.08,
    0.07,
    "8–40 ft",
    "Piers, beach, nearshore",
    "Pier and beach water on the northern Banks. Fall is drum, blues, and albacore. If the surf is ugly, drop back into the sound.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Fall bulls in the trough and along the pier."),
      sp("Bluefish", [4, 5, 9, 10, 11], "Choppers with the mullet run."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Fast metals just off the beach."),
      sp("False albacore", [9, 10, 11], "Tiny metals when they crash bait."),
      sp("Speckled trout", [4, 5, 10, 11], "Sound side, not in the surf."),
      sp("King mackerel", [9, 10], "A short run off the beach in the fall."),
    ],
  ),
  ground(
    "roanoke",
    "Roanoke Sound",
    "outer-banks",
    "inshore",
    "protected",
    35.91,
    -75.67,
    0.08,
    0.09,
    "4–15 ft",
    "Sound grass, bridge",
    "Behind Nags Head and Manteo. Small-boat water. The ocean swell does not belong in this read.",
    [
      sp("Speckled trout", [4, 5, 10, 11], "Grass points at dawn on a moving tide."),
      sp("Red drum", [5, 6, 9, 10, 11], "Puppy drum on the flats."),
      sp("Flounder", [5, 6, 7, 8, 9], "Channel edges and the bridge."),
      sp("Striped bass", [12, 1, 2, 3], "Winter, when they push into the sound."),
    ],
  ),
  ground(
    "pamlico",
    "Pamlico Sound",
    "outer-banks",
    "inshore",
    "protected",
    35.45,
    -76.05,
    0.16,
    0.18,
    "6–20 ft",
    "Grass, shoals, guts",
    "The big sound behind the Banks. Wind chop matters more than ocean swell. A north or southwest breeze lays one side down.",
    [
      sp("Speckled trout", [4, 5, 10, 11], "The fall sound bite is the reason people come."),
      sp("Red drum", [5, 6, 9, 10, 11], "Puppies on the grass, a few bulls on the shoals."),
      sp("Flounder", [5, 6, 7, 8, 9], "Drift the deeper edges."),
      sp("Striped bass", [11, 12, 1, 2, 3], "Winter fish in the western sound."),
      sp("Bluefish", [5, 6, 9, 10], "With the bait schools."),
    ],
  ),
  ground(
    "ocracoke",
    "Ocracoke Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    35.07,
    -76.0,
    0.05,
    0.06,
    "8–30 ft",
    "Inlet, sloughs",
    "A shifting inlet between the sound and the ocean. Fish the sloughs on the last of the flood. Stay in the sound if the swell is up.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Sight-fish clear sloughs."),
      sp("Speckled trout", [4, 5, 10, 11], "Sound side of the inlet."),
      sp("Flounder", [5, 6, 7, 8, 9], "The channel on a drift."),
      sp("Bluefish", [9, 10], "Fall bait."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Ocean side on a calm day."),
    ],
  ),
  ground(
    "core-sound",
    "Core Sound",
    "outer-banks",
    "inshore",
    "protected",
    34.82,
    -76.35,
    0.1,
    0.1,
    "3–12 ft",
    "Grass, shell, creeks",
    "Down East water between the Banks and the mainland. Skinny, and it fishes best on a moving tide with a light breeze.",
    [
      sp("Speckled trout", [4, 5, 10, 11], "A classic fall trout sound."),
      sp("Red drum", [5, 6, 9, 10, 11], "Puppies along the grass."),
      sp("Flounder", [5, 6, 7, 8, 9], "Creek mouths."),
      sp("Sheepshead", [4, 5, 6, 10, 11], "Docks and shell with fiddlers."),
    ],
  ),
  ground(
    "cape-lookout",
    "Cape Lookout shoals",
    "outer-banks",
    "nearshore",
    "coastal",
    34.58,
    -76.52,
    0.08,
    0.09,
    "10–40 ft",
    "Shoals, cape, rips",
    "The cape bends the tide and stacks bait. Give the breakers room. Drum in the surf line, kings and cobia just outside.",
    [
      sp("Red drum", [4, 5, 10, 11], "Big fish on the shoals in spring and fall."),
      sp("Cobia", [5, 6, 7], "Buoys and rays on the way out."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Green water along the beach."),
      sp("King mackerel", [5, 6, 9, 10], "Slow-troll the color change."),
      sp("False albacore", [9, 10], "Fall, on small metals."),
    ],
  ),
  ground(
    "beaufort-inlet",
    "Beaufort Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    34.69,
    -76.67,
    0.05,
    0.06,
    "10–40 ft",
    "Inlet, port, jetties",
    "The Crystal Coast front door. Sheepshead and flounder on the rocks, drum and spanish on the shoulders. Watch the shipping channel.",
    [
      sp("Sheepshead", [4, 5, 6, 10, 11], "Fiddlers tight to the rocks."),
      sp("Flounder", [5, 6, 7, 8, 9, 10], "Drift the inlet with a minnow."),
      sp("Red drum", [4, 5, 9, 10, 11], "Slot fish and a few bulls."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Along the beachfront."),
      sp("Cobia", [5, 6], "Sight-fishing on the way to the cape."),
      sp("Speckled trout", [4, 5, 10, 11], "Inside the inlet when the ocean is rough."),
    ],
  ),
  ground(
    "bogue",
    "Bogue Sound & Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    34.66,
    -77.02,
    0.06,
    0.1,
    "4–20 ft",
    "Sound, inlet, surf",
    "Emerald Isle and the sound behind it. The inlet is the ocean door. The sound is the bad-weather plan.",
    [
      sp("Speckled trout", [4, 5, 10, 11], "Sound grass and docks."),
      sp("Red drum", [5, 6, 9, 10, 11], "Inlet shoulders and the surf."),
      sp("Flounder", [5, 6, 7, 8, 9], "Inlet drift."),
      sp("Sheepshead", [4, 5, 10, 11], "Docks and the jetty rock."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Just off the beach."),
    ],
  ),
  ground(
    "big-rock",
    "Big Rock",
    "outer-banks",
    "offshore",
    "open",
    34.22,
    -76.2,
    0.12,
    0.16,
    "100–600 ftm",
    "Ledge, Gulf Stream edge",
    "The Morehead fleet's blue water, out past the 90 and toward the stream. Leave a weather window. This is not a pin to run to.",
    [
      sp("Yellowfin tuna", [4, 5, 6, 7, 8, 9, 10], "Troll at dawn, chunk if they stay."),
      sp("Blue marlin", [6, 7, 8], "The June tournament is famous. The fish are here in summer."),
      sp("White marlin", [7, 8, 9], "In the spread with the tuna."),
      sp("Mahi", [5, 6, 7, 8, 9], "Weedlines on the way out."),
      sp("Wahoo", [8, 9, 10], "High-speed at first light."),
      sp("Blackfin tuna", [5, 6, 7, 8, 9], "Small feathers."),
    ],
  ),
  ground(
    "new-river",
    "New River Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    34.55,
    -77.34,
    0.05,
    0.06,
    "6–25 ft",
    "Inlet, surf, nearshore",
    "Topsail and the inlet. Fish the inlet and the beach. The upper river is a military range — stay in the public inlet and surf.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Surf and inlet in the fall."),
      sp("Speckled trout", [4, 5, 10, 11], "Inside on a northeast blow."),
      sp("Flounder", [5, 6, 7, 8, 9], "Inlet channel."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Along the beach."),
      sp("Bluefish", [9, 10], "With the mullet."),
    ],
  ),
  ground(
    "wrightsville",
    "Wrightsville & Masonboro",
    "outer-banks",
    "inshore",
    "coastal",
    34.19,
    -77.79,
    0.06,
    0.07,
    "6–30 ft",
    "Inlets, piers, beach",
    "Two inlets and a pier. Kings show up just off the beach in the fall. Masonboro is the small-boat inlet — respect the ebb.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Inlet and surf."),
      sp("Speckled trout", [4, 5, 10, 11], "The creeks behind the beach."),
      sp("King mackerel", [9, 10], "Slow-troll live bait just offshore."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Beach pods."),
      sp("Flounder", [5, 6, 7, 8, 9], "Both inlets."),
      sp("Sheepshead", [4, 5, 10, 11], "The pier pilings and rocks."),
    ],
  ),
  ground(
    "cape-fear",
    "Cape Fear & Bald Head",
    "outer-banks",
    "nearshore",
    "coastal",
    33.85,
    -77.97,
    0.07,
    0.08,
    "10–50 ft",
    "Cape, river mouth, shoals",
    "The river meets the ocean at Bald Head and Oak Island. Shoals move. Use the markers. Drum and kings use the same tide rip.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Shoals and the beach in spring and fall."),
      sp("King mackerel", [5, 6, 9, 10], "The nearshore color change."),
      sp("Cobia", [5, 6], "Buoys in late spring."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Along the beach."),
      sp("Flounder", [5, 6, 7, 8, 9], "The river mouth."),
      sp("Sheepshead", [4, 5, 10, 11], "Jetties and dock pilings."),
      sp("Striped bass", [12, 1, 2, 3], "Winter, up the river, not on the shoals."),
    ],
  ),
  ground(
    "frying-pan",
    "Frying Pan Tower",
    "outer-banks",
    "nearshore",
    "open",
    33.49,
    -77.59,
    0.08,
    0.1,
    "40–70 ft",
    "Tower, live bottom",
    "About 30 miles off Cape Fear. A short offshore run, not a canyon. Kings live here in season. Leave time to get home.",
    [
      sp("King mackerel", [5, 6, 9, 10], "Live bait around the tower."),
      sp("Cobia", [5, 6], "Sight-fish the legs and nearby buoys."),
      sp("Amberjack", [5, 6, 7, 8, 9], "On the structure. Check the size rule."),
      sp("Mahi", [6, 7, 8], "Weed on the ride out."),
      sp("Black sea bass", [1, 2, 3, 4, 5, 10, 11, 12], "Bottom around the tower."),
      sp("Grouper", [5, 6, 7, 8], "Only if the season is open."),
    ],
  ),
  ground(
    "charleston-jetty",
    "Charleston jetties",
    "southeast",
    "inshore",
    "coastal",
    32.73,
    -79.85,
    0.06,
    0.08,
    "10–35 ft",
    "Jetties, harbor mouth",
    "The jetties fish like a reef that reaches the beach. Live shrimp and fiddlers. Watch the ship traffic.",
    [
      sp("Sheepshead", [3, 4, 5, 10, 11], "Fiddlers in the rocks."),
      sp("Red drum", [4, 5, 9, 10, 11], "Slot reds along the rocks."),
      sp("Black drum", [3, 4, 5], "Spring, on crab."),
      sp("Flounder", [4, 5, 6, 9, 10], "Mud minnows at the base."),
      sp("Trout", [4, 5, 10, 11], "Harbor creeks when the ocean is rough."),
    ],
  ),
  ground(
    "georgetown",
    "Georgetown reef",
    "southeast",
    "nearshore",
    "coastal",
    33.15,
    -78.95,
    0.1,
    0.12,
    "40–90 ft",
    "Live bottom, ledges",
    "A nearshore reef run. Bottom fish the ledges, troll the top for kings when the water is blue-green.",
    [
      sp("Black sea bass", [1, 2, 3, 4, 5, 10, 11, 12], "The dependable bottom fish."),
      sp("Vermilion snapper", [5, 6, 7, 8, 9], "Small baits on the ledges."),
      sp("King mackerel", [4, 5, 6, 9, 10], "Slow-troll the color."),
      sp("Cobia", [4, 5, 6], "Buoys on the way out."),
      sp("Grouper", [5, 6, 7, 8], "Know the season before you drop."),
    ],
  ),
  ground(
    "charleston-ledge",
    "Charleston Hole & ledge",
    "southeast",
    "offshore",
    "open",
    32.4,
    -78.7,
    0.16,
    0.22,
    "150–400 ft",
    "Ledge, Gulf Stream water",
    "The ledge is the southeast's easy offshore. Bottom fish it, or troll the edge when the stream pushes in.",
    [
      sp("Wahoo", [4, 5, 6, 9, 10], "High-speed at dawn."),
      sp("Mahi", [5, 6, 7, 8], "Weed and rips."),
      sp("Yellowfin tuna", [4, 5, 6], "Blackfins more often than yellowfin; both show up."),
      sp("Blackfin tuna", [4, 5, 6, 7], "Small feathers."),
      sp("Grouper", [4, 5, 6, 7, 8], "Bottom. Seasons open and close — check them."),
    ],
  ),
  ground(
    "sebastian",
    "Sebastian Inlet",
    "florida",
    "inshore",
    "coastal",
    27.86,
    -80.45,
    0.05,
    0.06,
    "6–20 ft",
    "Inlet, jetties, beach trough",
    "A small inlet with a big reputation. Snook and reds at the jetties; pompano in the trough when the surf is moderate.",
    [
      sp("Snook", [3, 4, 5, 6, 9, 10, 11], "Jetties at night on the moving tide. Handle them wet."),
      sp("Red drum", [1, 2, 3, 4, 9, 10, 11, 12], "Year-round, best on the tide swing."),
      sp("Pompano", [2, 3, 4, 10, 11], "Surf, small jigs in the trough."),
      sp("Spanish mackerel", [11, 12, 1, 2, 3], "Winter beach run."),
      sp("Tarpon", [5, 6, 7], "Migrating fish along the beach. Mostly release."),
    ],
  ),
  ground(
    "jupiter",
    "Jupiter reef",
    "florida",
    "nearshore",
    "coastal",
    26.94,
    -80.02,
    0.08,
    0.1,
    "60–120 ft",
    "Reef line, wrecks",
    "The reef is close. Drift the ledges for kings and sails in season; bottom fish when the current allows.",
    [
      sp("Sailfish", [11, 12, 1, 2, 3], "The winter kite and live-bait fishery."),
      sp("King mackerel", [11, 12, 1, 2, 3, 4], "Slow-troll the reef edge."),
      sp("Mahi", [4, 5, 6], "Spring weed."),
      sp("Cobia", [3, 4, 5], "Rays and buoys."),
      sp("Mutton snapper", [5, 6, 7, 8], "The reef. Check Atlantic snapper rules."),
    ],
  ),
  ground(
    "islamorada",
    "Islamorada flats",
    "florida",
    "inshore",
    "protected",
    24.92,
    -80.64,
    0.08,
    0.1,
    "1–8 ft",
    "Flats, channels, bridges",
    "Push-pole water. Tarpon in the channels in spring, bones and permit on the flats. Don't run the flats at speed.",
    [
      sp("Tarpon", [3, 4, 5, 6, 7], "Channels and bridges. Release fishery."),
      sp("Bonefish", [1, 2, 3, 4, 5, 10, 11, 12], "Flood tide on the oceanside flats."),
      sp("Permit", [3, 4, 5, 6, 7], "Wrecks and flat edges. A hard fish. Worth it."),
      sp("Snook", [1, 2, 3, 4, 10, 11, 12], "Bridge shadows at night."),
      sp("Redfish", [1, 2, 3, 4, 9, 10, 11, 12], "Backcountry shorelines."),
    ],
  ),
  ground(
    "miami-blue",
    "Miami blue water",
    "florida",
    "offshore",
    "open",
    25.7,
    -79.85,
    0.16,
    0.22,
    "400–1200 ft",
    "Stream edge, weedlines",
    "The Gulf Stream is in sight of the skyline. Sailfish in winter, dolphin in spring and summer. Afternoon storms build fast.",
    [
      sp("Sailfish", [11, 12, 1, 2, 3], "Live ballyhoo and kites."),
      sp("Mahi", [4, 5, 6, 7, 8], "Weedlines. The dependable offshore meal."),
      sp("Blackfin tuna", [1, 2, 3, 4, 11, 12], "Low light on the color change."),
      sp("Swordfish", [4, 5, 6, 7], "Daytime deep. Specialized."),
      sp("Wahoo", [11, 12, 1, 2], "Winter high-speed."),
    ],
  ),
  ground(
    "boca-grande",
    "Boca Grande Pass",
    "florida",
    "inshore",
    "coastal",
    26.71,
    -82.26,
    0.06,
    0.07,
    "30–70 ft",
    "Pass, deep hole",
    "The tarpon pass. Crowded in May and June — be polite and don't anchor in the traffic. The rest of the year is snook, reds, and grouper nearby.",
    [
      sp("Tarpon", [4, 5, 6, 7], "The pass migration. Mostly release. Know the gear rules."),
      sp("Snook", [3, 4, 5, 9, 10, 11], "Beach and docks around the pass."),
      sp("Redfish", [1, 2, 3, 9, 10, 11, 12], "Back bays off the pass."),
      sp("Gag grouper", [6, 7, 8, 9], "Nearby wrecks when the season is open."),
      sp("Spanish mackerel", [3, 4, 10, 11], "Beach pods."),
    ],
  ),
  ground(
    "orange-beach",
    "Orange Beach nearshore",
    "gulf",
    "nearshore",
    "coastal",
    30.22,
    -87.55,
    0.08,
    0.12,
    "40–90 ft",
    "Reefs, gas platforms in sight",
    "Short run to reefs and small platforms. Live bait under a float for kings; bottom rigs for snapper when open.",
    [
      sp("Red snapper", [5, 6, 7, 8], "Federal and state seasons differ. Check before you go."),
      sp("King mackerel", [5, 6, 7, 8, 9, 10], "Float a menhaden."),
      sp("Cobia", [3, 4, 5], "Sight-fish the buoys in spring."),
      sp("Mangrove snapper", [5, 6, 7, 8, 9], "Small hooks, small baits."),
      sp("Triggerfish", [5, 6, 7, 8], "On the reefs with the snapper."),
    ],
  ),
  ground(
    "venice",
    "Venice lumps",
    "gulf",
    "offshore",
    "open",
    28.6,
    -89.4,
    0.18,
    0.22,
    "200–600 ft",
    "Lumps, rigs, river plume",
    "The Mississippi plume sets up a tuna bite that can be world-class and can also be mud. Watch the river height and the thunderstorms.",
    [
      sp("Yellowfin tuna", [4, 5, 6, 7, 8], "Chunk the lumps at dawn."),
      sp("Mahi", [5, 6, 7, 8], "Rigs and weed on the way."),
      sp("Blue marlin", [6, 7, 8], "Summer, when the water is blue outside the river."),
      sp("Wahoo", [5, 6, 9], "Around the rip."),
      sp("Swordfish", [6, 7, 8], "Night or deep daytime."),
    ],
  ),
  ground(
    "galveston",
    "Galveston jetties",
    "gulf",
    "inshore",
    "coastal",
    29.33,
    -94.73,
    0.06,
    0.08,
    "8–30 ft",
    "Jetties, beach gut",
    "The north and south jetties. Sheepshead in the rocks, trout in the guts, bulls in the fall surf when the bait is there.",
    [
      sp("Sheepshead", [2, 3, 4, 11, 12], "Shrimp and fiddlers in the rocks."),
      sp("Speckled trout", [3, 4, 5, 9, 10, 11], "Wading the guts on a light wind."),
      sp("Red drum", [9, 10, 11], "Bulls in the surf in fall."),
      sp("Spanish mackerel", [5, 6, 7], "Along the beach."),
      sp("Flounder", [10, 11], "Fall migration at the jetty mouth."),
    ],
  ),
  ground(
    "flower-gardens",
    "Flower Garden Banks",
    "gulf",
    "offshore",
    "open",
    27.9,
    -93.82,
    0.14,
    0.18,
    "60–400 ft",
    "Sanctuary banks",
    "A national marine sanctuary about 100 miles off Texas. Fishing is allowed with strict gear and anchoring rules. Read them before you leave the dock.",
    [
      sp("Red snapper", [6, 7, 8], "Only in the open season, and not on the coral."),
      sp("Wahoo", [5, 6, 7, 8], "Troll the edge of the bank."),
      sp("Mahi", [5, 6, 7], "Weed on the ride."),
      sp("Blackfin tuna", [5, 6, 7], "Around the rigs between here and the beach."),
      sp("Grouper", [6, 7, 8], "Season and sanctuary rules both apply."),
    ],
  ),
  ground(
    "barnegat",
    "Barnegat Inlet",
    "northeast",
    "inshore",
    "coastal",
    39.76,
    -74.1,
    0.05,
    0.06,
    "8–25 ft",
    "Inlet, south jetty",
    "A rough little inlet when the ebb meets an east swell. Fish the bay side if the ocean is white. South jetty for tog and bass in season.",
    [
      sp("Striped bass", [4, 5, 6, 10, 11], "Jetty plugs at dawn, eels at night."),
      sp("Fluke", [5, 6, 7, 8, 9], "Drift the inlet and the bay flats."),
      sp("Bluefish", [5, 6, 9, 10], "With the bass."),
      sp("Tautog", [10, 11, 12, 4], "Green crab in the rocks."),
      sp("Weakfish", [5, 6, 9], "Bay side when they show."),
    ],
  ),
  ground(
    "montauk",
    "Montauk Point",
    "northeast",
    "nearshore",
    "coastal",
    41.07,
    -71.86,
    0.07,
    0.09,
    "20–70 ft",
    "Rips, point, wrecks",
    "The rips off the point are the whole fishery. Bass and blues on the surface, fluke on the drifts behind the point. Give the rocks room.",
    [
      sp("Striped bass", [5, 6, 7, 9, 10, 11], "The fall run is the famous one. Dawn eels and plugs."),
      sp("Bluefish", [6, 7, 9, 10], "Gators in the rip. Wire leaders."),
      sp("Fluke", [6, 7, 8, 9], "Drift the backside."),
      sp("False albacore", [9, 10], "Tiny metals when they crash bait."),
      sp("Black sea bass", [6, 7, 8, 9, 10], "Wrecks in between."),
    ],
  ),
  ground(
    "hudson",
    "Hudson Canyon",
    "northeast",
    "offshore",
    "open",
    39.55,
    -72.35,
    0.18,
    0.24,
    "100–1000 ftm",
    "Canyon walls",
    "The northeast's home canyon. Long ride from Jersey or Long Island. Tilefish on the bottom year-round, tuna when the temp break sets up.",
    [
      sp("Yellowfin tuna", [6, 7, 8, 9], "Chunk and troll the mouth."),
      sp("Bigeye tuna", [8, 9, 10], "Night chunking. A specialist trip."),
      sp("Mahi", [7, 8], "Weed on the way out."),
      sp("White marlin", [7, 8, 9], "Late summer."),
      sp("Tilefish", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "Golden tiles on the mud. Deep and specific."),
      sp("Bluefin tuna", [9, 10], "Some years, on the inshore lumps before the canyon."),
    ],
  ),
  ground(
    "cape-cod-bay",
    "Cape Cod Bay",
    "northeast",
    "inshore",
    "protected",
    41.85,
    -70.35,
    0.14,
    0.16,
    "20–120 ft",
    "Bay, rips, beaches",
    "Protected from a southwest wind, exposed to a northeast. Stripers on the beaches in June, flounder early, tuna in the deep bay some summers.",
    [
      sp("Striped bass", [5, 6, 7, 9, 10], "Beach and estuary fish."),
      sp("Bluefish", [6, 7, 8, 9], "With the bass."),
      sp("Flounder", [4, 5, 6], "Early season in the harbors."),
      sp("Bluefin tuna", [7, 8, 9], "Some years in the deep bay. A different boat than the bass skiff."),
      sp("Bonito", [8, 9], "Small metals."),
    ],
  ),
  ground(
    "la-jolla",
    "La Jolla kelp",
    "pacific",
    "nearshore",
    "coastal",
    32.85,
    -117.28,
    0.05,
    0.06,
    "20–80 ft",
    "Kelp, canyon head",
    "Kelp bass, calico, and yellowtail when the water is warm. The canyon head is why pelagics come this close. Watch the divers.",
    [
      sp("Yellowtail", [5, 6, 7, 8, 9], "Live sardine or iron when birds are up."),
      sp("Kelp bass", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "The everyday fish. Check the size."),
      sp("Calico bass", [4, 5, 6, 7, 8, 9], "Same fishery, warmer months."),
      sp("White seabass", [4, 5, 6], "Squid at night in spring."),
      sp("Dorado", [8, 9], "Warm-water years, outside the kelp."),
    ],
  ),
  ground(
    "catalina",
    "Catalina & 14 Mile",
    "pacific",
    "offshore",
    "open",
    33.35,
    -118.45,
    0.12,
    0.16,
    "80–600 ft",
    "Island, bank",
    "A crossing, not a bay trip. Yellowtail and yellowfin in warm years on the bank; island kelp on the lee side if the channel is up.",
    [
      sp("Yellowtail", [5, 6, 7, 8, 9, 10], "The reason the boats run."),
      sp("Yellowfin tuna", [8, 9, 10], "Warm-water summers on the 14."),
      sp("Bluefin tuna", [6, 7, 8], "Some years, and they can be anywhere."),
      sp("Dorado", [8, 9], "Kelp paddies."),
      sp("White seabass", [4, 5, 6], "Island at night."),
    ],
  ),
  ground(
    "monterey",
    "Monterey Canyon",
    "pacific",
    "offshore",
    "open",
    36.72,
    -122.05,
    0.12,
    0.14,
    "50–1000 ftm",
    "Canyon wall, kelp edge",
    "The canyon starts inside the bay, which is why salmon, rockfish, and sometimes albacore are a short run. Afternoons get windy. Leave early.",
    [
      sp("Rockfish", [4, 5, 6, 7, 8, 9, 10, 11], "The reliable bottom bite. Depth rules change — check them."),
      sp("Chinook salmon", [5, 6, 7, 8], "When the season is open. Troll the color."),
      sp("Lingcod", [4, 5, 10, 11], "With the rockfish, bigger iron."),
      sp("Albacore", [8, 9], "Warm years, outside."),
      sp("Halibut", [5, 6, 7], "Sand inside the bay."),
    ],
  ),
  ground(
    "grays",
    "Grays Harbor",
    "pacific",
    "nearshore",
    "coastal",
    46.9,
    -124.18,
    0.08,
    0.1,
    "20–80 ft",
    "Bar, nearshore, jetties",
    "The bar is the hazard. Cross only on a fair tide and a modest swell, or fish the jetties and the harbor. Salmon and lingcod outside when it's civil.",
    [
      sp("Chinook salmon", [6, 7, 8, 9], "Buoy 2 and the nearshore, in season."),
      sp("Coho salmon", [7, 8, 9], "Just outside, when they're in."),
      sp("Lingcod", [4, 5, 6, 7], "Reefs on a calm day."),
      sp("Black rockfish", [4, 5, 6, 7, 8, 9], "The everyday nearshore fish."),
      sp("Dungeness crab", [12, 1, 2, 3], "Pots, in the winter season. Not a rod fishery."),
    ],
  ),
  ground(
    "radio-island",
    "Radio Island",
    "outer-banks",
    "inshore",
    "protected",
    34.721,
    -76.685,
    0.02,
    0.02,
    "6–20 ft",
    "Spoil bank, creek mouth",
    "A short idle from Morehead. Trout and drum on the bank when the ocean is too rough to run the inlet. Confirm the channel with the chart, not this pin.",
    [
      sp("Speckled trout", [4, 5, 10, 11], "Often this time of year inside. Check the proclamation before you keep one."),
      sp("Red drum", [4, 5, 9, 10, 11], "Slot fish on the bank edges."),
      sp("Flounder", [5, 6, 7, 8, 9, 10], "Along the drop. Season changes by proclamation."),
    ],
  ),
  ground(
    "cape-fear-approaches",
    "Cape Fear approaches",
    "outer-banks",
    "nearshore",
    "open",
    33.89,
    -78.01,
    0.06,
    0.07,
    "15–40 ft",
    "Shipping channel, shoals",
    "The river meets the ocean here. Give the ship channel room and do not treat the pin as the bar. Kings and spanish when the water is clean.",
    [
      sp("King mackerel", [5, 6, 9, 10], "Outside the shoals, not in the channel."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Along the beach color."),
      sp("Red drum", [4, 5, 10, 11], "Shoals on a rising tide, with eyes on the swell."),
    ],
  ),
  ground(
    "lockwoods-folly",
    "Lockwoods Folly Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    33.92,
    -78.23,
    0.03,
    0.04,
    "4–15 ft",
    "Shallow inlet, marsh",
    "Thin water inside. This pin is the approach, not a surveyed path across the bar.",
    [
      sp("Red drum", [4, 5, 9, 10, 11], "Marsh edges when you can float."),
      sp("Flounder", [5, 6, 7, 8, 9], "Creek mouths. Check the proclamation."),
      sp("Speckled trout", [4, 5, 10, 11], "Inside, not on the ocean bar."),
    ],
  ),
  ground(
    "little-river-inlet",
    "Little River Inlet",
    "outer-banks",
    "inshore",
    "coastal",
    33.85,
    -78.55,
    0.04,
    0.05,
    "8–25 ft",
    "Inlet, ICW, jetties",
    "The NC/SC line is right here. ICW traffic mixes with inlet swell. NC rules on the north side, SC rules on the south.",
    [
      sp("Flounder", [5, 6, 7, 8, 9], "Jetties and the edges. Confirm which state's rules you are under."),
      sp("Sheepshead", [4, 5, 6, 10, 11], "Fiddlers on the rocks."),
      sp("Spanish mackerel", [6, 7, 8, 9], "Just outside on a calm morning."),
    ],
  ),
  ground(
    "myrtle-ar",
    "Myrtle Beach artificial reefs",
    "outer-banks",
    "nearshore",
    "open",
    33.68,
    -78.72,
    0.08,
    0.08,
    "30–60 ft",
    "Published reef material",
    "A planning pin for the Myrtle nearshore reefs, not a surveyed reef coordinate. Use the state's latest reef list before you anchor.",
    [
      sp("Black sea bass", [1, 2, 3, 4, 5, 10, 11, 12], "Bottom on the material. Check the federal or state rule for where you are sitting."),
      sp("King mackerel", [5, 6, 9, 10], "Troll the reef line, not through traffic."),
      sp("Cobia", [5, 6], "Sight-fish on calm days. Season is a proclamation, not this calendar."),
    ],
  ),
];

export function groundById(id: string): Ground {
  return GROUNDS.find((g) => g.id === id) ?? GROUNDS[0]!;
}

export function groundsIn(region: RegionId | "all", band: Band | "all"): Ground[] {
  return GROUNDS.filter((g) => (region === "all" || g.region === region) && (band === "all" || g.band === band));
}

export const BAND_LABEL: Record<Band, string> = {
  inshore: "Inshore",
  nearshore: "Nearshore",
  offshore: "Offshore",
};

export const BAND_BLURB: Record<Band, string> = {
  inshore: "Bays, inlets, grass, bridges",
  nearshore: "A short run. Reefs, towers, shoals",
  offshore: "Canyons, stream, blue water",
};
